// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cookie } from "./Cookie";

export type CookieJar = { id: string, workspaceId: string, name: string, cookies: Array<Cookie>, createdAt: bigint, updatedAt: bigint, };
