// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cookie = { id: string, name: string, value: string, domain: string, path: string, expiresAt: bigint | null, secure: boolean, httpOnly: boolean, };
