// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";

export type Environment = { id: string, workspaceId: string, parentId: string | null, name: string, color: string | null, variables: Array<KeyValue>, sortPriority: bigint, createdAt: bigint, updatedAt: bigint, };
