// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Folder = { id: string, workspaceId: string, parentId: string | null, name: string, sortPriority: bigint, createdAt: bigint, updatedAt: bigint, };
