// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpBodyRead = { content: string, offset: bigint, nextOffset: bigint, eof: boolean, isText: boolean, };
