// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpResponse } from "./HttpResponse";
import type { HttpResponseState } from "./HttpResponseState";

export type HttpStateEvent = { taskId: string, responseId: string, state: HttpResponseState, response: HttpResponse | null, };
