// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpProgress = { taskId: string, responseId: string, sentBytes: bigint, receivedBytes: bigint, status: number, statusText: string, contentType: string | null, bodyChunk: Array<number>, };
