// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpResponseState = "initialized" | "connecting" | "streaming" | "closed" | "cancelled" | "failed";
