// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { RequestAuth } from "./RequestAuth";
import type { RequestBody } from "./RequestBody";

export type HttpRequest = { id: string, workspaceId: string, folderId: string | null, name: string, method: string, url: string, parameters: Array<KeyValue>, headers: Array<KeyValue>, body: RequestBody, authentication: RequestAuth, timeoutMs: bigint, sortPriority: bigint, createdAt: bigint, updatedAt: bigint, };
