// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpResponseState } from "./HttpResponseState";
import type { KeyValue } from "./KeyValue";

export type HttpResponse = { id: string, requestId: string, workspaceId: string, taskId: string, state: HttpResponseState, method: string, url: string, status: number | null, statusText: string | null, requestHeaders: Array<KeyValue>, headers: Array<KeyValue>, bodyPath: string | null, bodySize: bigint, contentType: string | null, elapsedMs: bigint | null, errorCode: string | null, errorDetail: string | null, createdAt: bigint, updatedAt: bigint, };
