// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieJar } from "./CookieJar";
import type { Environment } from "./Environment";
import type { Folder } from "./Folder";
import type { HttpRequest } from "./HttpRequest";
import type { Settings } from "./Settings";
import type { Workspace } from "./Workspace";

export type Model = { "model": "settings", "data": Settings } | { "model": "workspace", "data": Workspace } | { "model": "folder", "data": Folder } | { "model": "environment", "data": Environment } | { "model": "cookie_jar", "data": CookieJar } | { "model": "http_request", "data": HttpRequest };
