// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";
import type { ModelKind } from "./ModelKind";
import type { ModelOperation } from "./ModelOperation";

export type ModelChange = { sequence: bigint, sourceWindowId: string, operation: ModelOperation, modelKind: ModelKind, modelId: string, workspaceId: string | null, model: Model | null, };
