// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelKind = "settings" | "workspace" | "folder" | "environment" | "cookie_jar" | "http_request";
