// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";

export type RequestBody = { "type": "none" } | { "type": "text", "value": string } | { "type": "json", "value": string } | { "type": "form", "value": Array<KeyValue> };
