// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestAuth = { "type": "none" } | { "type": "inherit" } | { "type": "basic", username: string, password: string, } | { "type": "bearer", token: string, prefix: string, } | { "type": "api_key", name: string, value: string, location: string, };
