// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";

export type Settings = { id: string, locale: string, appearance: Appearance, themeLight: string, themeDark: string, createdAt: bigint, updatedAt: bigint, };
