// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieJar } from "./CookieJar";
import type { Environment } from "./Environment";
import type { Folder } from "./Folder";
import type { HttpRequest } from "./HttpRequest";
import type { Settings } from "./Settings";
import type { Workspace } from "./Workspace";

export type WorkspaceSnapshot = { sequence: bigint, settings: Settings, workspaces: Array<Workspace>, folders: Array<Folder>, environments: Array<Environment>, cookieJars: Array<CookieJar>, httpRequests: Array<HttpRequest>, };
